# Make a dataframe. Shuffle teh data values. Slice columns maths,phy,chem using loc. Find the mean of tjree columns. Filter the name of students having mean og PCM >= 60

In [8]:
import pandas as pd
import numpy as np
import random

In [20]:
mark = np.arange(41,101)
random.shuffle(mark)
mark= mark.reshape(12,5)
print(mark)

[[ 68  89  80  70  53]
 [ 60  49  45  66  72]
 [ 62  58  94  97  65]
 [ 41  96  75  99  79]
 [ 54  50  82  92  74]
 [ 46  56  98  63  61]
 [ 86  55  43  93  83]
 [ 42  59  48  84  81]
 [ 85  47  71 100  78]
 [ 91  88  44  87  73]
 [ 51  76  77  57  90]
 [ 95  52  67  64  69]]


In [22]:
print(mark)

[[ 68  89  80  70  53]
 [ 60  49  45  66  72]
 [ 62  58  94  97  65]
 [ 41  96  75  99  79]
 [ 54  50  82  92  74]
 [ 46  56  98  63  61]
 [ 86  55  43  93  83]
 [ 42  59  48  84  81]
 [ 85  47  71 100  78]
 [ 91  88  44  87  73]
 [ 51  76  77  57  90]
 [ 95  52  67  64  69]]


In [24]:
names = ['a','b','c','d','e','f','g','h','i','j','k','l']
subject=['hindi','english','maths','physics','chemistry']

In [26]:
grade= pd.DataFrame(data=mark , index=names , columns=subject)

In [28]:
grade

hindi  english  maths  physics  chemistry
a     68       89     80       70         53
b     60       49     45       66         72
c     62       58     94       97         65
d     41       96     75       99         79
e     54       50     82       92         74
f     46       56     98       63         61
g     86       55     43       93         83
h     42       59     48       84         81
i     85       47     71      100         78
j     91       88     44       87         73
k     51       76     77       57         90
l     95       52     67       64         69