# Creating Array Using List

In [42]:
import numpy as np

In [48]:
arr = np.array([1,2,3,4,5])

In [50]:
arr

array([1, 2, 3, 4, 5])

# Creating Array Using Tuple

In [52]:
arr1 = np.array((1,2,3,4,5))

In [54]:
arr1

array([1, 2, 3, 4, 5])

In [56]:
arr1.shape

(5,)

In [58]:
arr.shape

(5,)

In [60]:
type(arr1)

numpy.ndarray

# Acessing Element of 1d array

In [63]:
arr[0]

1

In [65]:
arr[-1]

5

# Slicing 1-d array

In [71]:
arr[0:3]

array([1, 2, 3])

In [77]:
arr[-3:-1]

array([3, 4])

In [83]:
arr[:5]

array([1, 2, 3, 4, 5])

In [85]:
arr[2:]

array([3, 4, 5])

In [89]:
marks = np.array([1,2,3,4,5,6,7,8,9,10])

In [91]:
marks[:5]

array([1, 2, 3, 4, 5])

In [93]:
marks[5:]

array([ 6,  7,  8,  9, 10])

In [95]:
marks[-4:-2]

array([7, 8])

# Creating 2-d Array

In [106]:
array2 = np.array([[1,2,3,4],[5,6,7,8]])

In [108]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
array2.shape

(2, 4)

# Creating 2-d using Tuple

In [113]:
arr2 = np.array(((1,2,3),(4,5,6)))

In [115]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
type(array2)

numpy.ndarray

In [121]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
array2[1][1]

6

In [145]:
array2[0:1, 1:3]

array([[2, 3]])