# Slicing 2-d array

In [643]:
import numpy as np

In [644]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [645]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [646]:
arr.shape

(3, 4)

# Accessing specific elements of 2-d array- array[rows,columns]

In [648]:
arr[1,3]

8

In [649]:
arr[:,3]

array([ 4,  8, 12])

In [650]:
arr[:,2]

array([ 3,  7, 11])

In [651]:
arr[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [652]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [653]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [654]:
arr[1:2,1:4]

array([[6, 7, 8]])

# Creating all zeroes matrix

In [656]:
a= np.zeros((3,4), dtype="int64")

In [657]:
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [658]:
a = np.zeros((3,4), dtype="float64")

In [659]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Creating all 1s Matrix

In [661]:
b= np.ones((4,5) ,dtype="int32")

# print(b)

In [663]:
b[:,0:3]=10

In [664]:
print(b)

[[10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]]


In [665]:
b[0:2, 3:5]=4

In [666]:
print(b)

[[10 10 10  4  4]
 [10 10 10  4  4]
 [10 10 10  1  1]
 [10 10 10  1  1]]


In [667]:
b[2:4 , 3:5] = 5

In [668]:
print(b)

[[10 10 10  4  4]
 [10 10 10  4  4]
 [10 10 10  5  5]
 [10 10 10  5  5]]


In [669]:
c= np.full (b.shape ,99)

In [670]:
print(c)

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [671]:
d= np.full_like(c,5)

In [672]:
print(d)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [673]:
n1 = np.ones((3,3), dtype="int32")

In [674]:
print(n1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [675]:
n2 = np.full_like(n1,2)

In [676]:
print(n2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [677]:
n3=n1+n2

In [678]:
print(n3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [679]:
n3=n1*n2

In [680]:
print(n3)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [681]:
n = n3*n2

In [682]:
print(n)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


# Creating 3-d array

In [684]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [685]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [686]:
arr[0,1,1]

5

In [687]:
arr[0,:, 1:3]

array([[2, 3],
       [5, 6]])

In [688]:
arr[:,1:3]

array([[[ 4,  5,  6]],

       [[10, 11, 12]]])

In [689]:
arr[:,:,1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [690]:
arr[:,:,1:3] = 10

In [691]:
print(arr)

[[[ 1 10 10]
  [ 4 10 10]]

 [[ 7 10 10]
  [10 10 10]]]


In [692]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [693]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [694]:
b = a.reshape(2,6)

In [695]:
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [696]:
b = a.reshape(3,4)

In [697]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [698]:
d = a.reshape(2,3,2)

In [699]:
print(d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Copying the array

In [701]:
x = a.copy()
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


 # copy vs view

In [703]:
x[3:6]= 10

In [704]:
print(x)

[ 1  2  3 10 10 10  7  8  9 10 11 12]


In [705]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [706]:
y = a.view()

In [707]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [708]:
y[4:10]=99

In [709]:
print(y)

[ 1  2  3  4 99 99 99 99 99 99 11 12]


In [710]:
print(a)

[ 1  2  3  4 99 99 99 99 99 99 11 12]


# Iterating Array's elements

In [712]:
for i in a :
    print(i)

1
2
3
4
99
99
99
99
99
99
11
12


In [713]:
for i in a:
    print(i+2)

3
4
5
6
101
101
101
101
101
101
13
14


# Iteration in 2-d array

In [715]:
b = a.reshape(4,3)

In [716]:
for i in b:
    print(i)

[1 2 3]
[ 4 99 99]
[99 99 99]
[99 11 12]


In [717]:
a = np.array([1,2,3,4,5])

In [718]:
b = np.array([6,7,8,9,10])

In [719]:
c= np.concatenate((a,b) , axis=0)

In [720]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


# joining 2-d array 

In [722]:
x= np.array([[1,2,3],[4,5,6]])

In [723]:
y = np.array([[7,8,9],[10,11,12]])

In [724]:
z= np.concatenate((x,y),axis=0)

In [725]:
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [726]:
w = np.concatenate((x,y), axis=1)

In [727]:
print(w)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# axis= 0 --> rows, axis=1--> columns

# sorting an array

In [733]:
arr2 = np.sort(arr)

In [735]:
print(arr2)

[[[ 1 10 10]
  [ 4 10 10]]

 [[ 7 10 10]
  [10 10 10]]]


# sorting 2-d array

In [753]:
a = arr.reshape(3,4)

In [755]:
print(a)

[[ 1 10 10  4]
 [10 10  7 10]
 [10 10 10 10]]


In [763]:
b = np.sort(a)

In [765]:
print(b)

[[ 1  4 10 10]
 [ 7 10 10 10]
 [10 10 10 10]]
