# Random Module

In [2]:
# numpy offers a random module to generate a random number

In [8]:
import numpy as np
from numpy import random

In [23]:
x= np.random.randint(100)

In [25]:
print(x)

39


# Generating arrays of random number

In [28]:
a = np.random.randint(100,size=5)

In [30]:
print(a)

[53 50 66 94 32]


# Generating 2-d array using random module

In [33]:
b = np.random.randint(100, size=(3,4))

In [35]:
print(b)

[[77 38 87 91]
 [12 14 29  6]
 [32 23 79 25]]


# Generating random float

In [42]:
c= random.rand()

In [44]:
print(c)

0.7065961098908645


# Generating random float

In [55]:
d= random.rand(5)

In [57]:
print(d)

[0.76362068 0.91615104 0.9413121  0.93985477 0.33392311]


# Generating 2-d float random array

In [60]:
float_array = random.rand(3,4)

In [62]:
print(float_array)

[[0.82019147 0.75258132 0.40414678 0.03871378]
 [0.82357105 0.93837439 0.45630798 0.75626633]
 [0.4836219  0.97425019 0.49147111 0.4162803 ]]


# Selecting a random number from a given array

In [69]:
rand_num = random.choice([2,3,4,5,67,87])

In [71]:
print(rand_num)

67


In [91]:
colors = ['red','green','blue','white','black','pink','yellow']

In [93]:
select_color= random.choice(colors)

In [95]:
print(select_color)

yellow


In [99]:
security_breaches = np.array([[0,5,1] ,[0,2,0] ,[1,1,2] ,[2,2,1], [0,0,0]])

In [101]:
print(security_breaches)

[[0 5 1]
 [0 2 0]
 [1 1 2]
 [2 2 1]
 [0 0 0]]


In [107]:
print(security_breaches.sum())

17

In [109]:
print(security_breaches.sum(axis=1)) #aggregrating columns

[6 2 4 5 0]


In [111]:
print(security_breaches.sum(axis=0)) # aggregrating rows

[ 3 10  4]


In [113]:
print(security_breaches.min())

0


In [115]:
print(security_breaches.min(axis=0))

[0 0 0]


In [117]:
print(security_breaches.min(axis=1))

[0 0 1 1 0]


In [119]:
print(security_breaches.max())

5


In [121]:
print(security_breaches.max(axis=0))

[2 5 2]


In [125]:
print(security_breaches.max(axis=1))

[5 2 2 2 0]


# Finding mean

In [128]:
print(security_breaches.mean())

1.1333333333333333


In [130]:
print(security_breaches.mean(axis=1))

[2.         0.66666667 1.33333333 1.66666667 0.        ]


In [132]:
print(security_breaches.mean(axis=0))

[0.6 2.  0.8]


In [144]:
print(security_breaches.sum(axis=1, keepdims= True))

[[6]
 [2]
 [4]
 [5]
 [0]]


In [148]:
array= np.array([[1,2,3],[4,5,6]])

In [150]:
array*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [152]:
array*7

array([[ 7, 14, 21],
       [28, 35, 42]])

In [154]:
array*4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [162]:
array=np.array([[1,2,3],[4,5,6]])

In [166]:
array1= np.array([[7,8,9],[10,11,12]])

In [170]:
array+array1

array([[ 8, 10, 12],
       [14, 16, 18]])

In [172]:
array=np.array([[1,2,3],[4,5,6]])

In [174]:
array1=np.array([[0,1,0],[1,0,1]])

In [176]:
array*array1

array([[0, 2, 0],
       [4, 0, 6]])

# Not Just for maths

In [179]:
array=np.array([[1,2,3],[4,5,6]])

In [181]:
array>2

array([[False, False,  True],
       [ True,  True,  True]])

# Vectorised Python Code

In [184]:
array= np.array(["NumPy","is","Awesome"])

In [186]:
len(array)>2

True

In [188]:
vectorized_len=np.vectorize(len)

In [190]:
vectorized_len(array)>2

array([ True, False,  True])