# Pandas

# pandas is a python library used for manipulation of data sets. It has function for data analysis, manipulation, exploration and visualization

In [200]:
import pandas as pd
import numpy as np
import random

In [201]:
series1=pd.Series([10,20,30] , index=['x','y','z'])

In [202]:
print(series1)

x    10
y    20
z    30
dtype: int64


In [203]:
type(series1)

pandas.core.series.Series

# DataFrame

# dataframe is a datastructure that stores the data in two dimensional form.

In [206]:
# mark = np.arange(61,91).reshape(6,5)
mark = np.arange(61,91)
shuffle(mark)
mark= mark.reshape(6,5)
print(mark)

[[87 62 88 89 82]
 [79 70 67 64 90]
 [76 73 77 84 66]
 [65 80 63 78 71]
 [85 86 69 81 75]
 [61 68 74 72 83]]


In [207]:
print(mark)

[[87 62 88 89 82]
 [79 70 67 64 90]
 [76 73 77 84 66]
 [65 80 63 78 71]
 [85 86 69 81 75]
 [61 68 74 72 83]]


In [208]:
names = ['nitin','manvi','kanika','sahil','uttam','prince']
subject=['hindi','english','maths','physics','chemistry']

In [209]:
grade= pd.DataFrame(data=mark , index=names , columns=subject)

In [210]:
grade

hindi  english  maths  physics  chemistry
nitin      87       62     88       89         82
manvi      79       70     67       64         90
kanika     76       73     77       84         66
sahil      65       80     63       78         71
uttam      85       86     69       81         75
prince     61       68     74       72         83

In [211]:
grade.head(3)

hindi  english  maths  physics  chemistry
nitin      87       62     88       89         82
manvi      79       70     67       64         90
kanika     76       73     77       84         66

In [212]:
grade.tail(2)

hindi  english  maths  physics  chemistry
uttam      85       86     69       81         75
prince     61       68     74       72         83

grade.info()

In [214]:
grade.describe()

hindi    english      maths    physics  chemistry
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   75.500000  73.166667  73.000000  78.000000  77.833333
std    10.540398   8.635199   8.876936   8.921883   8.795832
min    61.000000  62.000000  63.000000  64.000000  66.000000
25%    67.750000  68.500000  67.500000  73.500000  72.000000
50%    77.500000  71.500000  71.500000  79.500000  78.500000
75%    83.500000  78.250000  76.250000  83.250000  82.750000
max    87.000000  86.000000  88.000000  89.000000  90.000000

# creating DataFrame using Dictionary

In [216]:
dict={
    'Name':['Aashih','Harsh','MunnaBahi','Circuit'],
    'Roll_No':[1001,1002,1003,1004],
    'Age':[18,19,20,21]
}

In [217]:
students= pd.DataFrame(dict)

In [218]:
print(students)

        Name  Roll_No  Age
0     Aashih     1001   18
1      Harsh     1002   19
2  MunnaBahi     1003   20
3    Circuit     1004   21


# Creating data frame using csv file

In [237]:
df = pd.read_csv("dogs.csv")
df.head()

Unnamed: 0   Dog Breed Group                                Height  \
0            Afador  Mixed Breed Dogs                       20 to 29 inches   
1       Affenhuahua  Mixed Breed Dogs                        6 to 12 inches   
2     Affenpinscher    Companion Dogs   9 to 11 inches tall at the shoulder   
3      Afghan Hound        Hound Dogs  24 to 26 inches tall at the shoulder   
4  Airedale Terrier      Terrier Dogs  21 to 23 inches tall at the shoulder   

            Weight       Life Span  Adaptability  \
0  50 to 75 pounds  10 to 12 years           NaN   
1   4 to 12 pounds  13 to 18 years           NaN   
2    7 to 9 pounds  12 to 14 years           NaN   
3  50 to 60 pounds  10 to 12 years           NaN   
4  40 to 65 pounds  10 to 13 years           NaN   

   Adapts Well To Apartment Living  Good For Novice Owners  Sensitivity Level  \
0                                1                       1                  3   
1                                4                       4                  4   
2                                5                       4                  3   
3                                5                       3                  5   
4                                1                       2                  3   

   Tolerates Being Alone  ...  Potential For Mouthiness  Prey Drive  \
0                      3  ...                         4         4.0   
1                      1  ...                         4         2.0   
2                      1  ...                         4         3.0   
3                      2  ...                         3         5.0   
4                      2  ...                         5         5.0   

   Tendency To Bark Or Howl  Wanderlust Potential  Physical Needs  \
0                       4.0                     4             NaN   
1                       4.0                     2             NaN   
2                       2.0                     2             NaN   
3                       2.0                     5             NaN   
4                       4.0                     4             NaN   

   Energy Level  Intensity  Exercise Needs  Potential For Playfulness  \
0             4          4               4                          3   
1             4          3               3                          3   
2             4          3               3                          4   
3             5          2               4                          4   
4             5          3               5                          5   

                         Detailed Description Link  
0            https://dogtime.com/dog-breeds/afador  
1       https://dogtime.com/dog-breeds/affenhuahua  
2     https://dogtime.com/dog-breeds/affenpinscher  
3      https://dogtime.com/dog-breeds/afghan-hound  
4  https://dogtime.com/dog-breeds/airedale-terrier  

[5 rows x 37 columns]

In [239]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Unnamed: 0                       392 non-null    object 
 1   Dog Breed Group                  392 non-null    object 
 2   Height                           389 non-null    object 
 3   Weight                           385 non-null    object 
 4   Life Span                        392 non-null    object 
 5   Adaptability                     0 non-null      float64
 6   Adapts Well To Apartment Living  392 non-null    int64  
 7   Good For Novice Owners           392 non-null    int64  
 8   Sensitivity Level                392 non-null    int64  
 9   Tolerates Being Alone            392 non-null    int64  
 10  Tolerates Cold Weather           392 non-null    int64  
 11  Tolerates Hot Weather            392 non-null    int64  
 12  All Around Friendlines

# slicing DataFrame

In [257]:
df1= df.loc[:,['Dog Breed Group','Height','Weight','Life Span']]
df1

Dog Breed Group                                             Height  \
0    Mixed Breed Dogs                                    20 to 29 inches   
1    Mixed Breed Dogs                                     6 to 12 inches   
2      Companion Dogs                9 to 11 inches tall at the shoulder   
3          Hound Dogs               24 to 26 inches tall at the shoulder   
4        Terrier Dogs               21 to 23 inches tall at the shoulder   
..                ...                                                ...   
387     Sporting Dogs               20 to 24 inches tall at the shoulder   
388    Companion Dogs  1 foot, 6 inches to 1 foot, 11 inches tall at ...   
389      Working Dogs                                    20 to 23 inches   
390       Hybrid Dogs                7 to 15 inches tall at the shoulder   
391    Companion Dogs                 8 to 9 inches tall at the shoulder   

              Weight       Life Span  
0    50 to 75 pounds  10 to 12 years  
1     4 to 12 pounds  13 to 18 years  
2      7 to 9 pounds  12 to 14 years  
3    50 to 60 pounds  10 to 12 years  
4    40 to 65 pounds  10 to 13 years  
..               ...             ...  
387  50 to 60 pounds  10 to 14 years  
388  10 to 50 pounds  14 to 20 years  
389  40 to 55 pounds  10 to 12 years  
390   3 to 14 pounds  10 to 15 years  
391    4 to 6 pounds  12 to 15 years  

[392 rows x 4 columns]

In [280]:
df2=df1.sort_values('Dog Breed Group')

In [282]:
df2.head(50)

Dog Breed Group                                             Height  \
391  Companion Dogs                 8 to 9 inches tall at the shoulder   
341  Companion Dogs               13 to 17 inches tall at the shoulder   
57   Companion Dogs                9 to 11 inches tall at the shoulder   
333  Companion Dogs               10 to 15 inches tall at the shoulder   
69   Companion Dogs                9 to 12 inches tall at the shoulder   
79   Companion Dogs               12 to 15 inches tall at the shoulder   
314  Companion Dogs               10 to 14 inches tall at the shoulder   
308  Companion Dogs     From 10 to over 22 inches tall at the shoulder   
92   Companion Dogs                                   22 to 30 inches.   
93   Companion Dogs                 7 to 8 inches tall at the shoulder   
100  Companion Dogs               12 to 15 inches tall at the shoulder   
293  Companion Dogs                 6 to 9 inches tall at the shoulder   
114  Companion Dogs                    12 to 13 inches at the shoulder   
289  Companion Dogs                8 to 11 inches tall at the shoulder   
124  Companion Dogs          6 inches to 9 inches tall at the shoulder   
126  Companion Dogs               11 to 13 inches tall at the shoulder   
271  Companion Dogs               10 to 12 inches tall at the shoulder   
264  Companion Dogs                8 to 10 inches tall at the shoulder   
182  Companion Dogs               11 to 12 inches tall at the shoulder   
175  Companion Dogs                                    20 to 24 Inches   
172  Companion Dogs               10 to 11 inches tall at the shoulder   
216  Companion Dogs                8 to 11 inches tall at the shoulder   
230  Companion Dogs               13 to 15 inches tall at the shoulder   
235  Companion Dogs                8 to 11 inches tall at the shoulder   
344  Companion Dogs                9 to 10 inches tall at the shoulder   
236  Companion Dogs                                    10 to 16 inches   
240  Companion Dogs  1 foot, 4 inches to 1 foot, 7 inches tall at t...   
151  Companion Dogs               19 to 24 inches tall at the shoulder   
146  Companion Dogs                8 to 12 inches tall at the shoulder   
137  Companion Dogs                                    17 to 20 inches   
261  Companion Dogs                9 to 11 inches tall at the shoulder   
263  Companion Dogs               12 to 14 inches tall at the shoulder   
238  Companion Dogs                                    17 to 22 inches   
345  Companion Dogs                                    17 to 22 inches   
305  Companion Dogs                7 to 12 inches tall at the shoulder   
194  Companion Dogs                                    12 to 15 inches   
388  Companion Dogs  1 foot, 6 inches to 1 foot, 11 inches tall at ...   
14   Companion Dogs               15 to 19 inches tall at the shoulder   
370  Companion Dogs                                    20 to 24 inches   
374  Companion Dogs                     8 to 11 inches at the shoulder   
352  Companion Dogs                9 to 10 inches tall at the shoulder   
372  Companion Dogs                From 10 inches tall at the shoulder   
373  Companion Dogs               14 to 16 inches tall at the shoulder   
2    Companion Dogs                9 to 11 inches tall at the shoulder   
10   Companion Dogs                                    13 to 17 inches   
321    Herding Dogs               15 to 21 inches tall at the shoulder   
27     Herding Dogs               17 to 20 inches tall at the shoulder   
173    Herding Dogs               16 to 20 inches tall at the shoulder   
366    Herding Dogs          11 inches to 13 inch tall at the shoulder   
167    Herding Dogs                                    21 to 25 inches   

                  Weight           Life Span  
391        4 to 6 pounds      12 to 15 years  
341      17 to 23 pounds      12 to 16 years  
57        7 to 12 pounds      12 to 15 years  
333      11 to 18 pounds      13 to 15 ye

In [ ]:
df2=df1.sort_values('Easy To Groom')

In [293]:
df2.head(50)

Dog Breed Group                                             Height  \
391  Companion Dogs                 8 to 9 inches tall at the shoulder   
341  Companion Dogs               13 to 17 inches tall at the shoulder   
57   Companion Dogs                9 to 11 inches tall at the shoulder   
333  Companion Dogs               10 to 15 inches tall at the shoulder   
69   Companion Dogs                9 to 12 inches tall at the shoulder   
79   Companion Dogs               12 to 15 inches tall at the shoulder   
314  Companion Dogs               10 to 14 inches tall at the shoulder   
308  Companion Dogs     From 10 to over 22 inches tall at the shoulder   
92   Companion Dogs                                   22 to 30 inches.   
93   Companion Dogs                 7 to 8 inches tall at the shoulder   
100  Companion Dogs               12 to 15 inches tall at the shoulder   
293  Companion Dogs                 6 to 9 inches tall at the shoulder   
114  Companion Dogs                    12 to 13 inches at the shoulder   
289  Companion Dogs                8 to 11 inches tall at the shoulder   
124  Companion Dogs          6 inches to 9 inches tall at the shoulder   
126  Companion Dogs               11 to 13 inches tall at the shoulder   
271  Companion Dogs               10 to 12 inches tall at the shoulder   
264  Companion Dogs                8 to 10 inches tall at the shoulder   
182  Companion Dogs               11 to 12 inches tall at the shoulder   
175  Companion Dogs                                    20 to 24 Inches   
172  Companion Dogs               10 to 11 inches tall at the shoulder   
216  Companion Dogs                8 to 11 inches tall at the shoulder   
230  Companion Dogs               13 to 15 inches tall at the shoulder   
235  Companion Dogs                8 to 11 inches tall at the shoulder   
344  Companion Dogs                9 to 10 inches tall at the shoulder   
236  Companion Dogs                                    10 to 16 inches   
240  Companion Dogs  1 foot, 4 inches to 1 foot, 7 inches tall at t...   
151  Companion Dogs               19 to 24 inches tall at the shoulder   
146  Companion Dogs                8 to 12 inches tall at the shoulder   
137  Companion Dogs                                    17 to 20 inches   
261  Companion Dogs                9 to 11 inches tall at the shoulder   
263  Companion Dogs               12 to 14 inches tall at the shoulder   
238  Companion Dogs                                    17 to 22 inches   
345  Companion Dogs                                    17 to 22 inches   
305  Companion Dogs                7 to 12 inches tall at the shoulder   
194  Companion Dogs                                    12 to 15 inches   
388  Companion Dogs  1 foot, 6 inches to 1 foot, 11 inches tall at ...   
14   Companion Dogs               15 to 19 inches tall at the shoulder   
370  Companion Dogs                                    20 to 24 inches   
374  Companion Dogs                     8 to 11 inches at the shoulder   
352  Companion Dogs                9 to 10 inches tall at the shoulder   
372  Companion Dogs                From 10 inches tall at the shoulder   
373  Companion Dogs               14 to 16 inches tall at the shoulder   
2    Companion Dogs                9 to 11 inches tall at the shoulder   
10   Companion Dogs                                    13 to 17 inches   
321    Herding Dogs               15 to 21 inches tall at the shoulder   
27     Herding Dogs               17 to 20 inches tall at the shoulder   
173    Herding Dogs               16 to 20 inches tall at the shoulder   
366    Herding Dogs          11 inches to 13 inch tall at the shoulder   
167    Herding Dogs                                    21 to 25 inches   

                  Weight           Life Span  
391        4 to 6 pounds      12 to 15 years  
341      17 to 23 pounds      12 to 16 years  
57        7 to 12 pounds      12 to 15 years  
333      11 to 18 pounds      13 to 15 ye

In [295]:
easy_groom = df1[df['Easy To Groom']>2]
easy_groom

Dog Breed Group                                             Height  \
1    Mixed Breed Dogs                                     6 to 12 inches   
2      Companion Dogs                9 to 11 inches tall at the shoulder   
5        Working Dogs                                    27 to 34 inches   
8    Mixed Breed Dogs                                    16 to 23 inches   
9    Mixed Breed Dogs                                    24 to 28 inches   
..                ...                                                ...   
386  Mixed Breed Dogs                                    12 to 20 inches   
387     Sporting Dogs               20 to 24 inches tall at the shoulder   
388    Companion Dogs  1 foot, 6 inches to 1 foot, 11 inches tall at ...   
389      Working Dogs                                    20 to 23 inches   
390       Hybrid Dogs                7 to 15 inches tall at the shoulder   

               Weight       Life Span  
1      4 to 12 pounds  13 to 18 years  
2       7 to 9 pounds  12 to 14 years  
5    75 to 140 pounds  10 to 12 years  
8     30 to 70 pounds  10 to 12 years  
9    75 to 120 pounds  10 to 13 years  
..                ...             ...  
386   20 to 45 pounds  12 to 15 years  
387   50 to 60 pounds  10 to 14 years  
388   10 to 50 pounds  14 to 20 years  
389   40 to 55 pounds  10 to 12 years  
390    3 to 14 pounds  10 to 15 years  

[288 rows x 4 columns]